'use strict';

/**
 * Declarative log-source signatures. Each signature is scored against a
 * sample of events; the highest-scoring signature above the confidence
 * floor is reported as the detected source. Purely rule-based / deterministic.
 *
 * - fieldHints: raw field names (case-insensitive substring match) that, if
 *   present anywhere in the flattened event, add weight.
 * - messagePatterns: regexes tested against the extracted primary message.
 * - datasetHints: values of event.dataset / event.module that strongly imply
 *   this source.
 */
const SOURCE_DEFINITIONS = [
  {
    name: 'Linux SSH',
    recommendedDataset: 'system.auth',
    importantFields: ['source.ip', 'user.name', 'event.action', 'event.outcome', '@timestamp'],
    fieldHints: ['sshd'],
    datasetHints: ['system.auth', 'sshd', 'auth'],
    messagePatterns: [/sshd/i, /failed password/i, /invalid user/i, /accepted password/i, /accepted publickey/i, /connection closed by/i],
    weight: 1,
  },
  {
    name: 'Windows Security',
    recommendedDataset: 'system.security',
    importantFields: ['winlog.event_id', 'user.name', 'winlog.event_data.TargetUserName', 'event.outcome', '@timestamp'],
    fieldHints: ['winlog.channel', 'winlog.event_id', 'targetusername', 'logontype'],
    datasetHints: ['windows.security', 'security'],
    messagePatterns: [/an account failed to log on/i, /an account was successfully logged on/i, /a logon was attempted/i, /special privileges assigned/i],
    channelHint: 'security',
    weight: 1,
  },
  {
    name: 'Windows Sysmon',
    recommendedDataset: 'windows.sysmon_operational',
    importantFields: ['process.name', 'process.command_line', 'process.parent.name', 'host.name', '@timestamp'],
    fieldHints: ['sysmon', 'utc time', 'commandline', 'parentimage', 'imageloaded'],
    datasetHints: ['windows.sysmon_operational', 'sysmon'],
    messagePatterns: [/sysmon/i, /process create/i, /network connection detected/i, /image loaded/i],
    channelHint: 'sysmon',
    weight: 1,
  },
  {
    name: 'Apache',
    recommendedDataset: 'apache.access',
    importantFields: ['source.ip', 'url.path', 'http.request.method', 'http.response.status_code', '@timestamp'],
    fieldHints: ['apache'],
    datasetHints: ['apache.access', 'apache.error'],
    messagePatterns: [/\[.*apache.*\]/i, /"(GET|POST|PUT|DELETE|HEAD) \/.*HTTP\/\d\.\d"/],
    weight: 1,
  },
  {
    name: 'Nginx',
    recommendedDataset: 'nginx.access',
    importantFields: ['source.ip', 'url.path', 'http.request.method', 'http.response.status_code', '@timestamp'],
    fieldHints: ['nginx'],
    datasetHints: ['nginx.access', 'nginx.error'],
    messagePatterns: [/nginx/i, /"(GET|POST|PUT|DELETE|HEAD) \/.*HTTP\/\d\.\d"/],
    weight: 0.95,
  },
  {
    name: 'IIS',
    recommendedDataset: 'iis.access',
    importantFields: ['source.ip', 'url.path', 'http.request.method', 'http.response.status_code', '@timestamp'],
    fieldHints: ['iis', 'cs-uri-stem', 'sc-status'],
    datasetHints: ['iis.access'],
    messagePatterns: [/cs-uri-stem/i, /w3svc/i],
    weight: 1,
  },
  {
    name: 'Fortinet Firewall',
    recommendedDataset: 'fortinet.firewall',
    importantFields: ['source.ip', 'destination.ip', 'destination.port', 'event.action', 'rule.name'],
    fieldHints: ['fortinet', 'fortigate'],
    datasetHints: ['fortinet.firewall'],
    messagePatterns: [/devname=/i, /fortigate/i, /policyid=/i],
    weight: 1,
  },
  {
    name: 'Palo Alto Firewall',
    recommendedDataset: 'panw.panos',
    importantFields: ['source.ip', 'destination.ip', 'destination.port', 'event.action', 'rule.name'],
    fieldHints: ['panw', 'paloalto', 'panos'],
    datasetHints: ['panw.panos'],
    messagePatterns: [/palo ?alto/i, /panw/i, /threat_id/i],
    weight: 1,
  },
  {
    name: 'Cisco Firewall',
    recommendedDataset: 'cisco.asa',
    importantFields: ['source.ip', 'destination.ip', 'destination.port', 'event.action'],
    fieldHints: ['asa', 'cisco'],
    datasetHints: ['cisco.asa', 'cisco.ftd'],
    messagePatterns: [/%asa-\d/i, /%ftd-\d/i, /cisco/i],
    weight: 1,
  },
  {
    name: 'Generic Firewall',
    recommendedDataset: 'network.firewall',
    importantFields: ['source.ip', 'destination.ip', 'destination.port', 'event.action', 'event.outcome'],
    fieldHints: ['firewall', 'deny', 'accept', 'action'],
    datasetHints: ['firewall'],
    messagePatterns: [/denied/i, /blocked/i, /firewall/i],
    weight: 0.7,
  },
  {
    name: 'DNS',
    recommendedDataset: 'network.dns',
    importantFields: ['dns.question.name', 'dns.question.type', 'source.ip', '@timestamp'],
    fieldHints: ['dns', 'query_name', 'qtype', 'resolve'],
    datasetHints: ['network.dns'],
    messagePatterns: [/dns query/i, /resolved/i],
    weight: 1,
  },
  {
    name: 'DHCP',
    recommendedDataset: 'network.dhcp',
    importantFields: ['source.ip', 'client.ip', 'host.name'],
    fieldHints: ['dhcp', 'lease'],
    datasetHints: ['network.dhcp'],
    messagePatterns: [/dhcp/i, /lease/i, /offered/i],
    weight: 1,
  },
  {
    name: 'VPN',
    recommendedDataset: 'network.vpn',
    importantFields: ['source.ip', 'user.name', 'event.action', 'event.outcome'],
    fieldHints: ['vpn', 'tunnel'],
    datasetHints: ['network.vpn'],
    messagePatterns: [/vpn/i, /tunnel established/i, /ipsec/i],
    weight: 1,
  },
  {
    name: 'Proxy',
    recommendedDataset: 'network.proxy',
    importantFields: ['source.ip', 'url.domain', 'http.response.status_code'],
    fieldHints: ['proxy', 'squid'],
    datasetHints: ['network.proxy', 'squid'],
    messagePatterns: [/proxy/i, /squid/i, /cache_/i],
    weight: 1,
  },
  {
    name: 'EDR / Endpoint',
    recommendedDataset: 'endpoint.events',
    importantFields: ['process.name', 'process.command_line', 'file.path', 'host.name'],
    fieldHints: ['endpoint', 'edr', 'crowdstrike', 'defender', 'carbonblack'],
    datasetHints: ['endpoint.events'],
    messagePatterns: [/endpoint/i, /malware detected/i, /quarantine/i],
    weight: 0.9,
  },
  {
    name: 'Generic Authentication',
    recommendedDataset: 'authentication',
    importantFields: ['user.name', 'event.outcome', 'event.action', 'source.ip'],
    fieldHints: ['login', 'logon', 'auth'],
    datasetHints: ['authentication'],
    messagePatterns: [/login (failed|succeeded)/i, /authentication (failed|succeeded)/i],
    weight: 0.6,
  },
  {
    name: 'AWS CloudTrail',
    recommendedDataset: 'aws.cloudtrail',
    importantFields: ['event.action', 'user.name', 'cloud.account.id', 'source.ip'],
    fieldHints: ['cloudtrail', 'eventsource', 'eventname', 'awsregion'],
    datasetHints: ['aws.cloudtrail'],
    messagePatterns: [/cloudtrail/i, /eventsource/i],
    weight: 1,
  },
  {
    name: 'Azure',
    recommendedDataset: 'azure.signinlogs',
    importantFields: ['user.name', 'event.outcome', 'source.ip', 'cloud.account.id'],
    fieldHints: ['azure', 'signinlogs', 'tenantid'],
    datasetHints: ['azure.signinlogs', 'azure.activitylogs'],
    messagePatterns: [/azure/i, /signinlogs/i],
    weight: 1,
  },
  {
    name: 'Microsoft 365',
    recommendedDataset: 'o365.audit',
    importantFields: ['user.name', 'event.action', 'source.ip'],
    fieldHints: ['o365', 'microsoft365', 'exchangeonline', 'sharepoint'],
    datasetHints: ['o365.audit'],
    messagePatterns: [/office ?365/i, /microsoft 365/i, /exchange online/i],
    weight: 1,
  },
  {
    name: 'Database',
    recommendedDataset: 'database.audit',
    importantFields: ['user.name', 'event.action', 'source.ip'],
    fieldHints: ['sql', 'database', 'query', 'mysql', 'postgres', 'mssql'],
    datasetHints: ['database.audit'],
    messagePatterns: [/failed login for user/i, /sql error/i, /slow query/i],
    weight: 0.6,
  },
  {
    name: 'Custom Application',
    recommendedDataset: 'application',
    importantFields: ['message', '@timestamp'],
    fieldHints: [],
    datasetHints: [],
    messagePatterns: [],
    weight: 0.1,
  },
];

module.exports = { SOURCE_DEFINITIONS };
