'use strict';

/**
 * A practical, wide subset of the Elastic Common Schema (ECS) - covering
 * every field group commonly seen in real Elastic exports (agent, client,
 * data_stream, destination, dns, ecs, elastic_agent, event, file, host,
 * http, input, log, network, observer, organization, os (via host/user_agent),
 * process, related, rule, server, service, source, threat, tls, url, user,
 * user_agent). Each entry documents the canonical ECS field, its ECS data
 * type, and a human description used in mapping-reason text. This is
 * intentionally data, not code, so it is easy to extend without touching
 * mapping logic.
 *
 * This is NOT the complete ~1000-field ECS spec (some deeply nested/rare
 * groups like `vulnerability.*`, `code_signature.*`, `x509.*` are omitted)
 * but covers what real-world logs actually populate. Fields genuinely
 * outside ECS (Elasticsearch's own `_id`/`_index`/`_score` metadata, or an
 * application's custom fields like `session.*`) are correctly left unmapped
 * by design - see ELASTICSEARCH_METADATA_FIELDS below.
 */
const ECS_FIELDS = {
  '@timestamp': { type: 'date', description: 'Date/time when the event originated' },
  message: { type: 'match_only_text', description: 'Free-text log message' },
  tags: { type: 'keyword', description: 'List of keywords used to tag the event' },
  labels: { type: 'object', description: 'Custom key/value labels attached to the event' },

  // ---------- agent ----------
  'agent.ephemeral_id': { type: 'keyword', description: 'Ephemeral identifier of this agent process' },
  'agent.id': { type: 'keyword', description: 'Unique identifier of the shipping agent' },
  'agent.name': { type: 'keyword', description: 'Custom name of the shipping agent' },
  'agent.type': { type: 'keyword', description: 'Type of agent that shipped the event' },
  'agent.version': { type: 'keyword', description: 'Version of the shipping agent' },

  // ---------- elastic_agent ----------
  'elastic_agent.id': { type: 'keyword', description: 'Identifier of the Elastic Agent' },
  'elastic_agent.snapshot': { type: 'boolean', description: 'Whether the Elastic Agent build is a snapshot' },
  'elastic_agent.version': { type: 'keyword', description: 'Version of the Elastic Agent' },

  // ---------- data_stream ----------
  'data_stream.dataset': { type: 'constant_keyword', description: 'Data stream dataset name' },
  'data_stream.namespace': { type: 'constant_keyword', description: 'Data stream namespace' },
  'data_stream.type': { type: 'constant_keyword', description: 'Data stream type (logs, metrics, ...)' },

  // ---------- ecs ----------
  'ecs.version': { type: 'keyword', description: 'Version of ECS this event conforms to' },

  // ---------- input ----------
  'input.type': { type: 'keyword', description: 'Input type the event was collected from' },

  // ---------- event ----------
  'event.category': { type: 'keyword', description: 'High level event category (authentication, network, ...)' },
  'event.type': { type: 'keyword', description: 'Sub-categorization of the event (start, end, denied, ...)' },
  'event.action': { type: 'keyword', description: 'The action captured by the event' },
  'event.outcome': { type: 'keyword', description: 'Outcome of the event (success, failure, unknown)' },
  'event.dataset': { type: 'keyword', description: 'Dataset the event came from' },
  'event.module': { type: 'keyword', description: 'Module/integration that produced the event' },
  'event.severity': { type: 'long', description: 'Numeric severity of the event' },
  'event.risk_score': { type: 'float', description: 'Risk score assigned to the event' },
  'event.original': { type: 'keyword', description: 'Raw original event text' },
  'event.id': { type: 'keyword', description: 'Unique identifier for the event' },
  'event.kind': { type: 'keyword', description: 'High level classification (event, alert, metric, ...)' },
  'event.created': { type: 'date', description: 'When the event was generated by the pipeline' },
  'event.ingested': { type: 'date', description: 'When the event was ingested into Elasticsearch' },
  'event.duration': { type: 'long', description: 'Duration of the event in nanoseconds' },
  'event.reason': { type: 'keyword', description: 'Reason given by the source for the event' },
  'event.agent_id_status': { type: 'keyword', description: 'Whether the agent ID in this event is trusted' },
  'event.provider': { type: 'keyword', description: 'Source of the event (e.g. Windows event log provider)' },
  'event.code': { type: 'keyword', description: 'Identification code from the source (e.g. Windows event ID)' },

  // ---------- host ----------
  'host.name': { type: 'keyword', description: 'Hostname of the host' },
  'host.hostname': { type: 'keyword', description: 'Hostname as reported by the host' },
  'host.id': { type: 'keyword', description: 'Unique host identifier' },
  'host.ip': { type: 'ip', description: 'IP addresses of the host' },
  'host.mac': { type: 'keyword', description: 'MAC addresses of the host' },
  'host.architecture': { type: 'keyword', description: 'CPU architecture of the host' },
  'host.os.name': { type: 'keyword', description: 'Operating system name' },
  'host.os.family': { type: 'keyword', description: 'OS family (redhat, debian, windows, ...)' },
  'host.os.platform': { type: 'keyword', description: 'OS platform (short, lowercase name)' },
  'host.os.version': { type: 'keyword', description: 'OS version' },
  'host.os.kernel': { type: 'keyword', description: 'OS kernel version' },
  'host.os.build': { type: 'keyword', description: 'OS build number' },
  'host.os.type': { type: 'keyword', description: 'OS type (linux, windows, macos, ...)' },

  // ---------- source ----------
  'source.ip': { type: 'ip', description: 'IP address of the source of the event' },
  'source.port': { type: 'long', description: 'Source port' },
  'source.domain': { type: 'keyword', description: 'Source domain name' },
  'source.address': { type: 'keyword', description: 'Source network address' },
  'source.bytes': { type: 'long', description: 'Bytes sent from the source' },
  'source.packets': { type: 'long', description: 'Packets sent from the source' },
  'source.as.number': { type: 'long', description: 'Autonomous system number of the source' },
  'source.as.organization.name': { type: 'keyword', description: 'Autonomous system organization name of the source' },
  'source.geo.city_name': { type: 'keyword', description: 'Source geo city' },
  'source.geo.continent_name': { type: 'keyword', description: 'Source geo continent' },
  'source.geo.country_name': { type: 'keyword', description: 'Source geo country' },
  'source.geo.country_iso_code': { type: 'keyword', description: 'Source geo country ISO code' },
  'source.geo.region_name': { type: 'keyword', description: 'Source geo region' },
  'source.geo.region_iso_code': { type: 'keyword', description: 'Source geo region ISO code' },
  'source.geo.location': { type: 'geo_point', description: 'Source geo coordinates' },

  // ---------- destination ----------
  'destination.ip': { type: 'ip', description: 'IP address of the destination of the event' },
  'destination.port': { type: 'long', description: 'Destination port' },
  'destination.domain': { type: 'keyword', description: 'Destination domain name' },
  'destination.address': { type: 'keyword', description: 'Destination network address' },
  'destination.bytes': { type: 'long', description: 'Bytes sent to the destination' },
  'destination.packets': { type: 'long', description: 'Packets sent to the destination' },
  'destination.geo.country_name': { type: 'keyword', description: 'Destination geo country' },

  // ---------- client / server ----------
  'client.ip': { type: 'ip', description: 'IP address of the client' },
  'client.port': { type: 'long', description: 'Client port' },
  'client.address': { type: 'keyword', description: 'Client network address' },
  'client.domain': { type: 'keyword', description: 'Client domain name' },
  'server.ip': { type: 'ip', description: 'IP address of the server' },
  'server.port': { type: 'long', description: 'Server port' },
  'server.address': { type: 'keyword', description: 'Server network address' },
  'server.domain': { type: 'keyword', description: 'Server domain name' },

  // ---------- network ----------
  'network.protocol': { type: 'keyword', description: 'Application layer protocol' },
  'network.transport': { type: 'keyword', description: 'Transport layer protocol (tcp/udp)' },
  'network.type': { type: 'keyword', description: 'IP address family (ipv4/ipv6)' },
  'network.direction': { type: 'keyword', description: 'Direction of the network traffic' },
  'network.bytes': { type: 'long', description: 'Total bytes transferred' },

  // ---------- user ----------
  'user.name': { type: 'keyword', description: 'Short login name / username of the user' },
  'user.id': { type: 'keyword', description: 'Unique identifier of the user' },
  'user.domain': { type: 'keyword', description: 'Domain the user belongs to' },
  'user.email': { type: 'keyword', description: 'Email address of the user' },
  'user.full_name': { type: 'keyword', description: 'Full display name of the user' },
  'user.roles': { type: 'keyword', description: 'Roles/groups assigned to the user' },
  'user.target.name': { type: 'keyword', description: 'Target/impersonated username of the event' },

  // ---------- process ----------
  'process.name': { type: 'keyword', description: 'Process name' },
  'process.command_line': { type: 'wildcard', description: 'Full command line of the process' },
  'process.pid': { type: 'long', description: 'Process ID' },
  'process.parent.name': { type: 'keyword', description: 'Parent process name' },
  'process.executable': { type: 'keyword', description: 'Absolute path to the process executable' },
  'process.args': { type: 'keyword', description: 'Process command-line arguments' },

  // ---------- file ----------
  'file.path': { type: 'keyword', description: 'Full path of the file' },
  'file.name': { type: 'keyword', description: 'Name of the file' },
  'file.hash.sha256': { type: 'keyword', description: 'SHA-256 hash of the file' },
  'file.extension': { type: 'keyword', description: 'File extension' },
  'file.size': { type: 'long', description: 'File size in bytes' },

  // ---------- url ----------
  'url.original': { type: 'wildcard', description: 'Full unparsed URL' },
  'url.full': { type: 'wildcard', description: 'Full parsed/normalized URL' },
  'url.path': { type: 'wildcard', description: 'Path of the request' },
  'url.query': { type: 'keyword', description: 'Query string of the request' },
  'url.domain': { type: 'keyword', description: 'Domain of the URL' },
  'url.port': { type: 'long', description: 'Port of the URL' },
  'url.scheme': { type: 'keyword', description: 'Scheme of the URL (http, https, ...)' },
  'url.extension': { type: 'keyword', description: 'File extension from the URL path' },

  // ---------- http ----------
  'http.request.method': { type: 'keyword', description: 'HTTP request method' },
  'http.request.bytes': { type: 'long', description: 'HTTP request body size in bytes' },
  'http.request.mime_type': { type: 'keyword', description: 'MIME type of the request body' },
  'http.request.referrer': { type: 'keyword', description: 'HTTP referrer' },
  'http.request.id': { type: 'keyword', description: 'HTTP request identifier' },
  'http.response.status_code': { type: 'long', description: 'HTTP response status code' },
  'http.response.bytes': { type: 'long', description: 'HTTP response body size in bytes' },
  'http.response.mime_type': { type: 'keyword', description: 'MIME type of the response body' },
  'http.version': { type: 'keyword', description: 'HTTP protocol version' },

  // ---------- user_agent ----------
  'user_agent.original': { type: 'keyword', description: 'Unparsed user agent string' },
  'user_agent.name': { type: 'keyword', description: 'Parsed browser/client name' },
  'user_agent.version': { type: 'keyword', description: 'Parsed browser/client version' },
  'user_agent.device.name': { type: 'keyword', description: 'Parsed device name' },
  'user_agent.os.name': { type: 'keyword', description: 'Parsed operating system name' },
  'user_agent.os.version': { type: 'keyword', description: 'Parsed operating system version' },

  // ---------- dns ----------
  'dns.question.name': { type: 'keyword', description: 'DNS query name' },
  'dns.question.type': { type: 'keyword', description: 'DNS record type queried' },
  'dns.response_code': { type: 'keyword', description: 'DNS response code' },

  // ---------- tls ----------
  'tls.version': { type: 'keyword', description: 'TLS/SSL protocol version' },
  'tls.cipher': { type: 'keyword', description: 'TLS/SSL cipher suite negotiated' },
  'tls.client.server_name': { type: 'keyword', description: 'SNI hostname requested by the client' },

  // ---------- observer ----------
  'observer.name': { type: 'keyword', description: 'Name of the observing sensor/device' },
  'observer.vendor': { type: 'keyword', description: 'Vendor of the observing device' },
  'observer.product': { type: 'keyword', description: 'Product name of the observing device' },

  // ---------- rule ----------
  'rule.name': { type: 'keyword', description: 'Name of the rule/signature that triggered' },
  'rule.id': { type: 'keyword', description: 'Identifier of the rule/signature that triggered' },

  // ---------- related ----------
  'related.ip': { type: 'ip', description: 'All IPs related to the event' },
  'related.user': { type: 'keyword', description: 'All usernames related to the event' },
  'related.hosts': { type: 'keyword', description: 'All hostnames related to the event' },

  // ---------- threat ----------
  'threat.technique.id': { type: 'keyword', description: 'MITRE ATT&CK technique ID' },
  'threat.technique.name': { type: 'keyword', description: 'MITRE ATT&CK technique name' },
  'threat.tactic.id': { type: 'keyword', description: 'MITRE ATT&CK tactic ID' },
  'threat.tactic.name': { type: 'keyword', description: 'MITRE ATT&CK tactic name' },

  // ---------- cloud ----------
  'cloud.provider': { type: 'keyword', description: 'Cloud provider name' },
  'cloud.region': { type: 'keyword', description: 'Cloud region' },
  'cloud.account.id': { type: 'keyword', description: 'Cloud account identifier' },

  // ---------- organization ----------
  'organization.id': { type: 'keyword', description: 'Unique organization identifier' },
  'organization.name': { type: 'keyword', description: 'Organization name' },

  // ---------- service ----------
  'service.name': { type: 'keyword', description: 'Name of the service' },
  'service.type': { type: 'keyword', description: 'Type of the service' },
  'service.id': { type: 'keyword', description: 'Unique identifier of the service instance' },
  'service.environment': { type: 'keyword', description: 'Environment the service is running in' },

  // ---------- log ----------
  'log.level': { type: 'keyword', description: 'Log level of the message' },
  'log.logger': { type: 'keyword', description: 'Name of the logger that produced the message' },
  'log.original': { type: 'keyword', description: 'Original raw log line' },
  'log.file.path': { type: 'keyword', description: 'Path to the log file' },
};

/**
 * Fields Elasticsearch itself adds to a hit's flattened representation
 * (index metadata) - never part of ECS and never log content, so they are
 * intentionally excluded from mapping rather than left looking like an
 * unexplained gap.
 */
const ELASTICSEARCH_METADATA_FIELDS = new Set(['_id', '_index', '_score', '_type', '_ignored', '_routing', '_seq_no', '_primary_term', '_version']);

/**
 * Every top-level field-group name defined by the real ECS specification,
 * including groups this app's ECS_FIELDS subset above doesn't carry
 * individual fields for yet (container, dll, email, error, faas, group,
 * orchestrator, package, registry, vulnerability, x509, span, trace,
 * transaction, vlan, volume, device, as, code_signature, os). This list
 * exists purely to answer one question correctly: is an unrecognized raw
 * field's top-level namespace *part of ECS at all*, or is it the analyst's
 * own application-specific field? A field under a namespace here but not in
 * ECS_FIELDS is a genuine schema-subset gap ("unmapped"); a field under a
 * namespace that isn't here at all is someone's own custom field ("custom")
 * - see ecsMapper.js's suggestMapping().
 */
const ECS_NAMESPACES = new Set([
  'agent', 'as', 'client', 'cloud', 'code_signature', 'container', 'data_stream',
  'destination', 'device', 'dll', 'dns', 'ecs', 'elastic_agent', 'email', 'error',
  'event', 'faas', 'file', 'group', 'host', 'http', 'input', 'labels', 'log',
  'message', 'network', 'observer', 'orchestrator', 'organization', 'os', 'package',
  'process', 'registry', 'related', 'rule', 'server', 'service', 'source', 'span',
  'tags', 'threat', 'tls', 'trace', 'tracing', 'transaction', 'url', 'user',
  'user_agent', 'vlan', 'volume', 'vulnerability', 'x509',
]);

/** True if a raw field's top-level dotted segment is a real ECS field-group name (whether or not we carry specific sub-fields for it). */
function isKnownEcsNamespace(field) {
  const topLevel = String(field).split('.')[0];
  return topLevel === '@timestamp' || ECS_NAMESPACES.has(topLevel);
}

/**
 * Kibana/ECS commonly ship a `.text` multi-field alongside a keyword/wildcard
 * field purely to support full-text search (e.g. `host.name.text` next to
 * `host.name`). These are not separate ECS fields but ARE meaningfully
 * ECS-derived, so they get resolved by stripping the suffix rather than
 * reported as an unmapped gap.
 */
const TEXT_MULTIFIELD_SUFFIX = '.text';

function isKnownEcsField(field) {
  return Object.prototype.hasOwnProperty.call(ECS_FIELDS, field);
}

function getEcsFieldInfo(field) {
  return ECS_FIELDS[field] || null;
}

function isElasticsearchMetadataField(field) {
  return ELASTICSEARCH_METADATA_FIELDS.has(field);
}

/** Resolves a `.text` multi-field to its base ECS field, if the base is known. */
function resolveTextMultifield(field) {
  if (!field.endsWith(TEXT_MULTIFIELD_SUFFIX)) return null;
  const base = field.slice(0, -TEXT_MULTIFIELD_SUFFIX.length);
  return isKnownEcsField(base) ? base : null;
}

module.exports = {
  ECS_FIELDS,
  isKnownEcsField,
  getEcsFieldInfo,
  isElasticsearchMetadataField,
  resolveTextMultifield,
  isKnownEcsNamespace,
};
